version: '3'
services:
  service:
    container_name: customer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/postgres
      - DATABASE_USERNAME=sa
      - DATABASE_PASSWORD=sa.1
    networks:
      - app-network

networks:
  app-network:
    external: true
